import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={inter.className}
      style={{
        height: "100vh",
      }}
    >
      <AppRouterCacheProvider>
        {/* <ThemeProvider> */}
        {children}
        {/* </ThemeProvider> */}
      </AppRouterCacheProvider>
    </body>
  </html>
  );
}
